# Uncomment the next line to define a global platform for your project
platform :ios, '11.3'
pod 'AppCenter'
target 'app_center' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for app_center

#  target 'app_centerTests' do
#    inherit! :search_paths
#    # Pods for testing
#  end

#  target 'app_centerUITests' do
#    inherit! :search_paths
#    # Pods for testing
#  end

end
